apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::912410919946:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12S3O3R0PGHJV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::912410919946:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-19T05:56:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1405"
  uid: 2826d772-2719-458f-ac85-ec36db5020f4
